### ISSUE TITLE
Most news is unavailable

### ISSUE THREAD

**Issue by gdunstone** [OpenGovAus/iview-proxy#4]
I get a 503 from `iviewhlsvod-vh.akamaihd.net` for most "news" type content.

I am not sure why.

For example clip with id **TASM202013384710** - *ABC News Tasmania Extras - Taste of Tasmania festival future in doubt*

**Comment by king-millez** [comment]
Seems like it's only news clips that don't work, I can watch actual evening news broadcasts fine:
![image](https://user-images.githubusercontent.com/26447912/122160224-e1a32c80-ceb2-11eb-9a95-38f7d4b1576c.png)
